package project

// AppSkeleton app skeleton map
var AppSkeleton = func(mp string) map[string]string {
	return map[string]string{
		"/.gitignore":                                     "/skeleton/.gitignore.example",
		"/appdata/readme.md":                              "/skeleton/appdata/readme.md",
		"/config/readme.md":                               "/skeleton/config/readme.md",
		"/config/development.toml":                        "/skeleton/config/development.toml",
		"/config/loggers.toml":                            "/skeleton/config/loggers.toml",
		"/system/configskeleton/readme.md":                "/skeleton/system/configskeleton/readme.md",
		"/system/data/readme.md":                          "/skeleton/system/data/readme.md",
		"/test/testconfig/readme.md":                      "/skeleton/test/testconfig/readme.md",
		"/src/main.go":                                    "/skeleton/src/main.go",
		"/src/build/build-linux.sh":                       "/skeleton/src/build/build-linux.sh",
		"/src/build/publish-linux.sh":                     "/skeleton/src/build/publish-linux.sh",
		"/system/constants/presetworkers.toml":            "/skeleton/system/constants/presetworkers.toml",
		"/system/defaultconfig/time.toml":                 "/skeleton/system/defaultconfig/time.toml",
		"/system/defaultconfig/examples/time.toml":        "/skeleton/system/defaultconfig/examples/time.toml",
		"/system/defaultconfig/development.toml":          "/skeleton/system/defaultconfig/development.toml",
		"/system/defaultconfig/examples/development.toml": "/skeleton/system/defaultconfig/examples/development.toml",
		"/system/defaultconfig/loggers.toml":              "/skeleton/system/defaultconfig/loggers.toml",
		"/system/defaultconfig/workers.toml":              "/skeleton/system/defaultconfig/workers.toml",
		"/system/defaultconfig/readme.md":                 "/skeleton/system/defaultconfig/readme.md",
		"/system/defaultconfig/examples/loggers.toml":     "/skeleton/system/defaultconfig/examples/loggers.toml",
		"/system/defaultconfig/examples/readme.md":        "/skeleton/system/defaultconfig/examples/readme.md",
		"/system/defaultconfig/examples/workers.toml":     "/skeleton/system/defaultconfig/examples/workers.toml",
		"/resources/readme.md":                            "/skeleton/resources/readme.md",
		mp + "/init.go":                                   "/skeleton/src/modules/init.go",
		mp + "/panicid.go":                                "/skeleton/src/modules/panicid.go",
		mp + "/app/app.sync.go":                           "/skeleton/src/modules/app/app.sync.go",
		mp + "/app/development.go":                        "/skeleton/src/modules/app/development.go",
		mp + "/app/loggers.go":                            "/skeleton/src/modules/app/loggers.go",
		mp + "/app/app_test.go":                           "/skeleton/src/modules/app/app_test.go",
		mp + "/app/workers.go":                            "/skeleton/src/modules/app/workers.go",
		mp + "/app/presetworkers.go":                      "/skeleton/src/modules/app/presetworkers.go",
		mp + "/overseers/init.go":                         "/skeleton/src/modules/overseers/init.go",
		mp + "/hired/init.go":                             "/skeleton/src/modules/hired/init.go",
		mp + "/readme.md":                                 "/skeleton/src/modules/readme.md",
		// mp + "/go.mod":                            "/skeleton/src/modules/go.mod",
		mp + "/app/time.go":                   "/skeleton/src/modules/app/time.go",
		mp + "/appevents/appevents.go":        "/skeleton/src/modules/appevents/appevents.go",
		mp + "/appevents/registeredevents.go": "/skeleton/src/modules/appevents/registeredevents.go",
		mp + "/loggers/init.go":               "/skeleton/src/modules/loggers/init.go",
		mp + "/loggers/init_linux.go":         "/skeleton/src/modules/loggers/init_linux.go",
		mp + "/test/test.go":                  "/skeleton/src/modules/test/test.go",
		mp + "/test/init_test.go":             "/skeleton/src/modules/test/init_test.go",
		mp + "/test/readme.md":                "/skeleton/src/modules/test/readme.md",
		mp + "/test/tests/init.go":            "/skeleton/src/modules/test/tests/init.go",
		mp + "/test/tests/init_test.go":       "/skeleton/src/modules/test/tests/init_test.go",
		mp + "/test/tests/readme.md":          "/skeleton/src/modules/test/tests/readme.md",
		// mp + "/drivers/cache.go":              "/skeleton/src/modules/drivers/cache.go",
		// mp + "/drivers/marshaler.go":          "/skeleton/src/modules/drivers/marshaler.go",
		mp + "/drivers/database.go": "/skeleton/src/modules/drivers/database.go",
		mp + "/drivers/uniqueid.go": "/skeleton/src/modules/drivers/uniqueid.go",
	}
}
