[[Views]]
Name="testtemplate"
Description="test dsec"
Type="template"
[Views.Config]
Topic="test Topic"
Disabled=false
TTLInSeconds=3600
Delivery="tencentcloudsms"
Engine="handlebars"
[Views.Config.Constants]
"a"="15"
"b"="22"
[[Views.Config.Params]]
Source="userinfo"
target="user"
Parser="json"
Description="用户信息"
Example='''{"id":12345,"name":"abcd"}'''
[[Views.Config.Params]]
Source="mobile"
Description="手机号"
Example="13500000000"
[[Views.Config.Params]]
Source="usercode"
Target="code"
Description="验证码"
Example="abcdefg"
[Views.Config.HeaderTemplate]
"target"="{{{user.id}}}"
[Views.Config.ContentTemplate]
"templatecode"="123456"
"phonenumbers"="+86{{{commaescape mobile}}}"
"templatparams"="{{{commaescape code}}}"
